IANA_IPV4_REGISTRY = {
    0:   {"designation": "IANA - Local Identification",                "status": "RESERVED"},
    1:   {"designation": "APNIC",                                      "status": "ALLOCATED"},
    2:   {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    3:   {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    4:   {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    5:   {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    6:   {"designation": "Army Information Systems Center",            "status": "LEGACY"},
    7:   {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    8:   {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    9:   {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    10:  {"designation": "IANA - Private Use",                         "status": "RESERVED"},
    11:  {"designation": "DoD Intel Information Systems",              "status": "LEGACY"},
    12:  {"designation": "AT&T Bell Laboratories",                     "status": "LEGACY"},
    13:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    14:  {"designation": "APNIC",                                      "status": "ALLOCATED"},
    15:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    16:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    17:  {"designation": "Apple Computer Inc.",                        "status": "LEGACY"},
    18:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    19:  {"designation": "Ford Motor Company",                         "status": "LEGACY"},
    20:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    21:  {"designation": "DDN-RVN",                                    "status": "LEGACY"},
    22:  {"designation": "Defense Information Systems Agency",         "status": "LEGACY"},
    23:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    24:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    25:  {"designation": "Administered by RIPE NCC",                   "status": "LEGACY"},
    26:  {"designation": "Defense Information Systems Agency",         "status": "LEGACY"},
    27:  {"designation": "APNIC",                                      "status": "ALLOCATED"},
    28:  {"designation": "DSI-North",                                  "status": "LEGACY"},
    29:  {"designation": "Defense Information Systems Agency",         "status": "LEGACY"},
    30:  {"designation": "Defense Information Systems Agency",         "status": "LEGACY"},
    31:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    32:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    33:  {"designation": "DLA Systems Automation Center",              "status": "LEGACY"},
    34:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    35:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    36:  {"designation": "APNIC",                                      "status": "ALLOCATED"},
    37:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    38:  {"designation": "PSINet, Inc.",                               "status": "LEGACY"},
    39:  {"designation": "APNIC",                                      "status": "ALLOCATED"},
    40:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    41:  {"designation": "AFRINIC",                                    "status": "ALLOCATED"},
    42:  {"designation": "APNIC",                                      "status": "ALLOCATED"},
    43:  {"designation": "Administered by APNIC",                      "status": "LEGACY"},
    44:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    45:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    46:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    47:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    48:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    49:  {"designation": "APNIC",                                      "status": "ALLOCATED"},
    50:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    51:  {"designation": "Administered by RIPE NCC",                   "status": "LEGACY"},
    52:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    53:  {"designation": "Daimler AG",                                 "status": "LEGACY"},
    54:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    55:  {"designation": "DoD Network Information Center",             "status": "LEGACY"},
    56:  {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    57:  {"designation": "Administered by RIPE NCC",                   "status": "LEGACY"},
    58:  {"designation": "APNIC",                                      "status": "ALLOCATED"},
    59:  {"designation": "APNIC",                                      "status": "ALLOCATED"},
    60:  {"designation": "APNIC",                                      "status": "ALLOCATED"},
    61:  {"designation": "APNIC",                                      "status": "ALLOCATED"},
    62:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    63:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    64:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    65:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    66:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    67:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    68:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    69:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    70:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    71:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    72:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    73:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    74:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    75:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    76:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    77:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    78:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    79:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    80:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    81:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    82:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    83:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    84:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    85:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    86:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    87:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    88:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    89:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    90:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    91:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    92:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    93:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    94:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    95:  {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    96:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    97:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    98:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    99:  {"designation": "ARIN",                                       "status": "ALLOCATED"},
    100: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    101: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    102: {"designation": "AFRINIC",                                    "status": "ALLOCATED"},
    103: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    104: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    105: {"designation": "AFRINIC",                                    "status": "ALLOCATED"},
    106: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    107: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    108: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    109: {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    110: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    111: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    112: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    113: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    114: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    115: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    116: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    117: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    118: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    119: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    120: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    121: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    122: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    123: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    124: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    125: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    126: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    127: {"designation": "IANA - Loopback",                            "status": "RESERVED"},
    128: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    129: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    130: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    131: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    132: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    133: {"designation": "Administered by APNIC",                      "status": "LEGACY"},
    134: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    135: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    136: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    137: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    138: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    139: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    140: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    141: {"designation": "Administered by RIPE NCC",                   "status": "LEGACY"},
    142: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    143: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    144: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    145: {"designation": "Administered by RIPE NCC",                   "status": "LEGACY"},
    146: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    147: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    148: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    149: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    150: {"designation": "Administered by APNIC",                      "status": "LEGACY"},
    151: {"designation": "Administered by RIPE NCC",                   "status": "LEGACY"},
    152: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    153: {"designation": "Administered by APNIC",                      "status": "LEGACY"},
    154: {"designation": "Administered by AFRINIC",                    "status": "LEGACY"},
    155: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    156: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    157: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    158: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    159: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    160: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    161: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    162: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    163: {"designation": "Administered by APNIC",                      "status": "LEGACY"},
    164: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    165: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    166: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    167: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    168: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    169: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    170: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    171: {"designation": "Administered by APNIC",                      "status": "LEGACY"},
    172: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    173: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    174: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    175: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    176: {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    177: {"designation": "LACNIC",                                     "status": "ALLOCATED"},
    178: {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    179: {"designation": "LACNIC",                                     "status": "ALLOCATED"},
    180: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    181: {"designation": "LACNIC",                                     "status": "ALLOCATED"},
    182: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    183: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    184: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    185: {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    186: {"designation": "LACNIC",                                     "status": "ALLOCATED"},
    187: {"designation": "LACNIC",                                     "status": "ALLOCATED"},
    188: {"designation": "Administered by RIPE NCC",                   "status": "LEGACY"},
    189: {"designation": "LACNIC",                                     "status": "ALLOCATED"},
    190: {"designation": "LACNIC",                                     "status": "ALLOCATED"},
    191: {"designation": "Administered by LACNIC",                     "status": "LEGACY"},
    192: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    193: {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    194: {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    195: {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    196: {"designation": "Administered by AFRINIC",                    "status": "LEGACY"},
    197: {"designation": "AFRINIC",                                    "status": "ALLOCATED"},
    198: {"designation": "Administered by ARIN",                       "status": "LEGACY"},
    199: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    200: {"designation": "LACNIC",                                     "status": "ALLOCATED"},
    201: {"designation": "LACNIC",                                     "status": "ALLOCATED"},
    202: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    203: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    204: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    205: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    206: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    207: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    208: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    209: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    210: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    211: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    212: {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    213: {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    214: {"designation": "US-DOD",                                     "status": "LEGACY"},
    215: {"designation": "US-DOD",                                     "status": "LEGACY"},
    216: {"designation": "ARIN",                                       "status": "ALLOCATED"},
    217: {"designation": "RIPE NCC",                                   "status": "ALLOCATED"},
    218: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    219: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    220: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    221: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    222: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    223: {"designation": "APNIC",                                      "status": "ALLOCATED"},
    224: {"designation": "Multicast",                                  "status": "RESERVED"},
    225: {"designation": "Multicast",                                  "status": "RESERVED"},
    226: {"designation": "Multicast",                                  "status": "RESERVED"},
    227: {"designation": "Multicast",                                  "status": "RESERVED"},
    228: {"designation": "Multicast",                                  "status": "RESERVED"},
    229: {"designation": "Multicast",                                  "status": "RESERVED"},
    230: {"designation": "Multicast",                                  "status": "RESERVED"},
    231: {"designation": "Multicast",                                  "status": "RESERVED"},
    232: {"designation": "Multicast",                                  "status": "RESERVED"},
    233: {"designation": "Multicast",                                  "status": "RESERVED"},
    234: {"designation": "Multicast",                                  "status": "RESERVED"},
    235: {"designation": "Multicast",                                  "status": "RESERVED"},
    236: {"designation": "Multicast",                                  "status": "RESERVED"},
    237: {"designation": "Multicast",                                  "status": "RESERVED"},
    238: {"designation": "Multicast",                                  "status": "RESERVED"},
    239: {"designation": "Multicast",                                  "status": "RESERVED"},
    240: {"designation": "Future use",                                 "status": "RESERVED"},
    241: {"designation": "Future use",                                 "status": "RESERVED"},
    242: {"designation": "Future use",                                 "status": "RESERVED"},
    243: {"designation": "Future use",                                 "status": "RESERVED"},
    244: {"designation": "Future use",                                 "status": "RESERVED"},
    245: {"designation": "Future use",                                 "status": "RESERVED"},
    246: {"designation": "Future use",                                 "status": "RESERVED"},
    247: {"designation": "Future use",                                 "status": "RESERVED"},
    248: {"designation": "Future use",                                 "status": "RESERVED"},
    249: {"designation": "Future use",                                 "status": "RESERVED"},
    250: {"designation": "Future use",                                 "status": "RESERVED"},
    251: {"designation": "Future use",                                 "status": "RESERVED"},
    252: {"designation": "Future use",                                 "status": "RESERVED"},
    253: {"designation": "Future use",                                 "status": "RESERVED"},
    254: {"designation": "Future use",                                 "status": "RESERVED"},
    255: {"designation": "Future use",                                 "status": "RESERVED"},
}
